# Matriks Invers 
Matriks invers adalah matriks yang ketika dikalikan dengan A menghasilkan matiks identitas. Matriks invers dilambangkan dengan $A^-1$.
Secara sistematis dapat dituliskan dengan :

$A^-1$  x  A = I

dimana I adalah matriks identitas dengan dimensi yang sama dengan A.


## Sifat-sifat matriks Invers
Berikut beberapa Sifat-sifat matriks invers :
1.	Matriks invers hanya ada untuk matriks persegi, yaitu    matriks yang memiliki jumlah baris dan kolom yang sama.

2. Invers Matriks hanya ada untuk matriks nonsingular, yaitu matriks yang memiliki determinan tidak sama dengan nol

3. matriks invers adalah tunggal, yaitu tidak ada lebih dari satu matriks yang dapat menjadi invers dari suatu matriks. jika B dan C keduanya adalah invers dari A, maka B = C

## Mencari matriks invers dengan eliminasi Gauss Jordan
Metode eliminasi Gauss Jordan merupakan salah satu metode yang umum digunakan untuk mencari matriks invers. metode ini berkerja dengan mengubah matriks A menjadi matriks indentitas (I) menggunakan operasi baris elementer, dan mengubah matriks augmentasi (A | I) menjadi matriks yang berisi matriks invers $A^-1$ disebelah kanan

#### Contoh Mencari matriks Invers dengan eliminasi Gauss-Jordan :

Misalkan kita ingin mencari matriks invers dari matriks berikut dengan menuliskan matriks A dengan matriks identitas (I) disebelah kanannya

In [40]:
A = np.array([[2,2,1,1,0,0],[4,2,3,0,1,0],[1,3,-1,0,0,1]])
print(A)

[[ 2  2  1  1  0  0]
 [ 4  2  3  0  1  0]
 [ 1  3 -1  0  0  1]]


In [42]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

a = np.array([[1,1,0.5,0.5,0,0],[0,1,-0.5,1,-0.5,0],[0,0,1,5,-2,-2]])
print(a)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [43]:
b = RowScale(a,2,1/2)
print(b)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [44]:
c = RowAdd(b,2,1,1)
print(c)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [45]:
d = RowAdd(c,2,0,-1)
print(d)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [46]:
f = RowScale(d,2,2)
print(f)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [47]:
g = RowAdd(f,1,0,-1)
print(g)

[[ 1.   0.   0.  -5.5  2.5  2. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [48]:
b = np.array([[9],[17],[5]])

c = np.array([[-5.5,2.5,2],[3.5,-1.5,-1],[5,-2,-2]])

print(c@b)

[[3.]
 [1.]
 [1.]]


## penyelesaian sistem persamaan linier menggunakan matriks invers

Persamaan dengan 4 variabel :

$
x_1 + x_2 + x_3 + x_4 = 6\\
2x_1 + x_2 + 2x_3 + x_4 = 9\\
3x_1 + 2x_2 + x_3 + 2x_4 = 13\\
x_1 + 3x_2 + 3x_3 + 2x_4 = 12
$

$ A = 
\begin{bmatrix}
1 & 1 & 1 & 1\\
2 & 1 & 2 & 1\\
3 & 2 & 1 & 2\\
1 & 3 & 3 & 2
\end{bmatrix}
X =
\begin{bmatrix}
x_1 \\
x_2\\
x_3\\
x_4
\end{bmatrix}
B = 
\begin{bmatrix}
6\\
9\\
13\\
12
\end{bmatrix}
$


In [49]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

a = np.array([[1,1,1,1,1,0,0,0],[2,1,2,1,0,1,0,0],[3,2,1,2,0,0,1,0],[1,3,3,2,0,0,0,1]])
print(a)

[[1 1 1 1 1 0 0 0]
 [2 1 2 1 0 1 0 0]
 [3 2 1 2 0 0 1 0]
 [1 3 3 2 0 0 0 1]]


In [64]:
# Mengalikan -2 ke baris 0 dan menambahkan ke baris 1
b = RowAdd(a,0,1,-2)
print(b)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0. -1.  0. -1. -2.  1.  0.  0.]
 [ 3.  2.  1.  2.  0.  0.  1.  0.]
 [ 1.  3.  3.  2.  0.  0.  0.  1.]]


In [65]:
# Mengalikan -3 ke baris 0 dan menambahkan ke baris 2
c = RowAdd(b,0,2,-3)
print(c)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0. -1.  0. -1. -2.  1.  0.  0.]
 [ 0. -1. -2. -1. -3.  0.  1.  0.]
 [ 1.  3.  3.  2.  0.  0.  0.  1.]]


In [66]:
# Mengalikan -1 ke baris 0 dan menambahkan ke baris 3
d = RowAdd(c,0,3,-1)
print(d)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0. -1.  0. -1. -2.  1.  0.  0.]
 [ 0. -1. -2. -1. -3.  0.  1.  0.]
 [ 0.  2.  2.  1. -1.  0.  0.  1.]]


In [67]:
# Mengalikan 2 ke baris 1 dan menambahkan ke baris 3
e = RowAdd(d,1,3,2)
print(e)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0. -1.  0. -1. -2.  1.  0.  0.]
 [ 0. -1. -2. -1. -3.  0.  1.  0.]
 [ 0.  0.  2. -1. -5.  2.  0.  1.]]


In [68]:
# Mengalikan -1 ke baris 1 dan menambahkan ke baris 2
f = RowAdd(e,1,2,-1)
print(f)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0. -1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -2.  0. -1. -1.  1.  0.]
 [ 0.  0.  2. -1. -5.  2.  0.  1.]]


In [69]:
# Mengalikan 1 ke baris 2 dan menambahkan ke baris 3
g = RowAdd(f,2,3,1)
print(g)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 0. -1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -2.  0. -1. -1.  1.  0.]
 [ 0.  0.  0. -1. -6.  1.  1.  1.]]


In [70]:
# Mengalikan 0.5 ke baris 2
h = RowScale(g,2,0.5)
print(h)

[[ 1.   1.   1.   1.   1.   0.   0.   0. ]
 [ 0.  -1.   0.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.  -1.   0.  -0.5 -0.5  0.5  0. ]
 [ 0.   0.   0.  -1.  -6.   1.   1.   1. ]]


In [71]:
# Mengalikan 1 ke baris 1 dan menambahkan ke baris 0
i = RowAdd(h,1,0,1)
print(i)

[[ 1.   0.   1.   0.  -1.   1.   0.   0. ]
 [ 0.  -1.   0.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.  -1.   0.  -0.5 -0.5  0.5  0. ]
 [ 0.   0.   0.  -1.  -6.   1.   1.   1. ]]


In [72]:
# Mengalikan 1 ke baris 2 dan menambahkan ke baris 0
j = RowAdd(i,2,0,1)
print(j)

[[ 1.   0.   0.   0.  -1.5  0.5  0.5  0. ]
 [ 0.  -1.   0.  -1.  -2.   1.   0.   0. ]
 [ 0.   0.  -1.   0.  -0.5 -0.5  0.5  0. ]
 [ 0.   0.   0.  -1.  -6.   1.   1.   1. ]]


In [73]:
# Mengalikan -1 ke baris 3 dan menambahkan ke baris 1
k = RowAdd(j,3,1,-1)
print(k)

[[ 1.   0.   0.   0.  -1.5  0.5  0.5  0. ]
 [ 0.  -1.   0.   0.   4.   0.  -1.  -1. ]
 [ 0.   0.  -1.   0.  -0.5 -0.5  0.5  0. ]
 [ 0.   0.   0.  -1.  -6.   1.   1.   1. ]]


In [74]:
# Mengalikan -1 ke baris 1
l = RowScale(k,1,-1)
print(l)

[[ 1.   0.   0.   0.  -1.5  0.5  0.5  0. ]
 [-0.   1.  -0.  -0.  -4.  -0.   1.   1. ]
 [ 0.   0.  -1.   0.  -0.5 -0.5  0.5  0. ]
 [ 0.   0.   0.  -1.  -6.   1.   1.   1. ]]


In [75]:
# Mengalikan -1 ke baris 2
m = RowScale(l,2,-1)
print(m)

[[ 1.   0.   0.   0.  -1.5  0.5  0.5  0. ]
 [-0.   1.  -0.  -0.  -4.  -0.   1.   1. ]
 [-0.  -0.   1.  -0.   0.5  0.5 -0.5 -0. ]
 [ 0.   0.   0.  -1.  -6.   1.   1.   1. ]]


In [76]:
# Mengalikan -1 ke baris 3
n = RowScale(m,3,-1)
print(n)

[[ 1.   0.   0.   0.  -1.5  0.5  0.5  0. ]
 [-0.   1.  -0.  -0.  -4.  -0.   1.   1. ]
 [-0.  -0.   1.  -0.   0.5  0.5 -0.5 -0. ]
 [-0.  -0.  -0.   1.   6.  -1.  -1.  -1. ]]


In [63]:
o = np.array([[6],[9],[13],[12]])
p = np.array([[-1.5,0.5,0.5,0],[-4,-0,1,1],[0.5,0.5,-0.5,-0],[6,-1,-1,-1]])
print(p @ o)

[[2.]
 [1.]
 [1.]
 [2.]]
