# Konsep EigenValue dan EigenVector

Ketika terdapat matriks bujur sangkar A dengan derajat n. Jika terdapat vector tidak nol x dan skalar $\lambda$ sehingga 

$$Ax = \lambda x$$

maka $\lambda$ disebut EigenValue dari matriks A, dan X disebut EigenVector, sedangkan yang lainnya bersesuai dengan EigenValue $\lambda$.

untuk menemukan EigenValue, harus menyesuaikan :

$$det(A-\lambda)=0$$

Setelah mendapatkan $\lambda$, substitusikan kembali ke persamaan $(A-\lambda)x = 0$ untuk menemukan vector x.

## Contoh Hitung EigenValue dan EigenVector menggunakan Numpy

### Matriks 2 x 2

In [1]:
import numpy as np
from numpy.linalg import eig
A= np.array ([[1,4],[2,3]])
w,v = eig(A)
print(A,'\n')
print(w,'\n')
print(v)

[[1 4]
 [2 3]] 

[-1.  5.] 

[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Matriks 3 X 3

In [2]:
import numpy as np
from numpy.linalg import eig

# Matriks 3x3
A = np.array([[1,4,1],[2,3,2],[2,4,5]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w.round(), '\n')
print('E-value', v.round(), '\n')

[[1 4 1]
 [2 3 2]
 [2 4 5]] 

E-value [ 8. -1.  2.] 

E-value [[-0. -1. -1.]
 [-0.  0. -0.]
 [-1.  0.  1.]] 



# Implementasi EigenValue dan EigenVector

### Implementasi PCA melalui EVD dengan python:

In [7]:
import numpy as np

def pcaSVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)  # Pusatkan data

    u, sigma, vt = np.linalg.svd(X_centered, full_matrices=False)

    # Mengembalikan komponen utama dan eigenvalue
    return (X_centered @ vt.T), (sigma**2) / (n-1)

# Contoh Data
x = np.array([[1, 4], [2, 3]])

komponen_utama, eigenvalue = pcaSVD(x)
print("Matriks:\n",x,'\n')
print("Komponen utama:\n", komponen_utama.round(),'\n')
print("Eigenvalue:\n", eigenvalue.round())


Matriks:
 [[1 4]
 [2 3]] 

Komponen utama:
 [[-1.  0.]
 [ 1. -0.]] 

Eigenvalue:
 [1. 0.]
