# Determinan

Determinan merupakan ukuran skalar dari sebuah matriks. Determinan berlaku hanya untuk matriks bujur sangkar.

## Sifat-Sifat Determinan 

### 1. Detrminan dari matriks identitas adalah 1

In [2]:
import numpy as np
from numpy import linalg as LA

A = np.array ([[5,6],[9,8]])
B = np.array([[8,9,1],[1,2,3],[2,1,1]])
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(A,'\n')
print(B,'\n')
print(C,'\n')
print(D)

[[5 6]
 [9 8]] 

[[8 9 1]
 [1 2 3]
 [2 1 1]] 

[[1 0]
 [0 1]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
print(np.linalg.det(C))
print(np.linalg.det(D))

1.0
1.0


### 2. Determinan matriks (AB) = det(A).det(B)

In [4]:
E = np.array ([[3,5,1],[2,6,2],[1,3,1]])
F = np.array ([[1,1,2],[1,1,3],[2,1,2]])

print(E,'\n')
print(F)

[[3 5 1]
 [2 6 2]
 [1 3 1]] 

[[1 1 2]
 [1 1 3]
 [2 1 2]]


In [5]:
G = np.dot(E,F)
print(G,'\n')
print(np.linalg.det(G))

[[10  9 23]
 [12 10 26]
 [ 6  5 13]] 

0.0


In [6]:
E = np.array ([[3,5,1],[2,6,2],[1,3,1]])
print(E,'\n')
print("determinan =",round(np.linalg.det(E)))

[[3 5 1]
 [2 6 2]
 [1 3 1]] 

determinan = 0


In [7]:
F = np.array ([[1,1,2],[1,1,3],[2,1,2]])
print(F,'\n')
print("determinan =",round(np.linalg.det(F)))

[[1 1 2]
 [1 1 3]
 [2 1 2]] 

determinan = 1


### 3. Menukar baris dari matrix akan mengubah tanda dari determinan

In [11]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [12]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(A,'\n')
print("determinan =",round(np.linalg.det(A)))

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

determinan = 5


In [13]:
A1 = RowSwap(A,0,1)
print(A1,'\n')
print("determinan =",round(np.linalg.det(A1)))

[[1. 1. 1.]
 [1. 4. 2.]
 [3. 2. 1.]] 

determinan = -5


### 4. Jika baris atau dari matrix merupakan kelipatan dari barisatau kolom yang lain maka hasil detrminannya akan sama dengan 0

In [14]:
A2 = np.array([[1,4,2],[2,8,4],[3,2,1]])
print(A2,'\n')
print("determinan =",round(np.linalg.det(A2)))

[[1 4 2]
 [2 8 4]
 [3 2 1]] 

determinan = 0


In [15]:
A3 = np.array([[1,4,2],[2,8,3],[1,4,1]])
print(A3,'\n')
print("determinan =",round(np.linalg.det(A3)))

[[1 4 2]
 [2 8 3]
 [1 4 1]] 

determinan = 0


### 5. Apabila determinan skalar k dan determinan matriks A dikalikan maka, det (kA) = k^n det(A)

In [16]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
k = 2
n = np.dot(A,k)
print(A,'\n')
print("determinan =",round(np.linalg.det(A)),'\n')
print(n)

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

determinan = 5 

[[2 8 4]
 [2 2 2]
 [6 4 2]]


In [17]:
kA = np.dot(2**3,5)
print(kA)

40


In [18]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
B = np.array([[2,8,4],[1,1,1],[3,2,1]])

print("determinan =",round(np.linalg.det(B)),'\n')

determinan = 10 



## Matriks Segitiga Atas
yaitu matriks yang nilai dibawah diagonal utama adalah 0

maka hasil determinannya merupakan hasil perkalian dari setiap diagona

In [19]:
A = np.array([[2,3,1,2],[0,1,2,1],[0,0,5,2],[0,0,0,3]])
print(A,'\n')
print("determinan =",round(np.linalg.det(A)))

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]] 

determinan = 30


Melakukan operasi pada matriks tidak merubah determinan pada matriks

In [20]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [21]:
A1 = RowAdd(A,0,1,-1)
print(A1)

[[ 1.  4.  2.]
 [ 0. -3. -1.]
 [ 3.  2.  1.]]


In [22]:
print("determinan =",round(np.linalg.det(A1)))

determinan = 5


Determinan A transnpose sama dengan determinan A

In [23]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
A_transpose = A.T
print(A,'\n')
print("determinan =",round(np.linalg.det(A)),'\n')
print(A_transpose,'\n')
print("determinan =",round(np.linalg.det(A_transpose)))

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

determinan = 5 

[[1 1 3]
 [4 1 2]
 [2 1 1]] 

determinan = 5


## Ekspansi Kofaktor 
Salah satu metode mencari detrminan matriks, dimana dalam metode ini memanfaatkan kofaktor.

Pencarian determinan menggunakan metode ini tidak terbatas dengan satu ukuran matriks.

Dengan kata lain, dapat dihitung matriks 3x3, 4x4, 5x5, dan seterusnya

Contoh Menghitung determinan matriks 4 x 4 menggunakan ekspansi kofaktor

$ A = 
\begin{bmatrix}
1 & 4 & 2 & 3\\
0 & 1 & 4 & 4\\
-1 & 0 & 1 & 1\\
2 & 0 & 4 & 1
\end{bmatrix}
$
= a11c11 + a12c12 + a13c13 + a14c14

$(-1)^{1+1} 
det = 
\begin{bmatrix}
1 & 4 & 4\\
0 & 1 & 1 \\
0 & 4 & 1\\
\end{bmatrix}
$

$(-1)^{1+2} 
det = 
\begin{bmatrix}
0 & 4 & 4\\
-1 & 1 & 1 \\
2 & 4 & 1\\
\end{bmatrix}
$

$(-1)^{1+3} 
det = 
\begin{bmatrix}
0 & 1 & 4\\
-1 & 0 & 1 \\
2 & 0 & 1\\
\end{bmatrix}
$

$(-1)^{1+4} 
det = 
\begin{bmatrix}
0 & 1 & 4\\
-1 & 0 & 1 \\
2 & 0 & 4\\
\end{bmatrix}
$

$
c11 = 
\begin{bmatrix}
1 & 4 & 4\\
0 & 1 & 1 \\
0 & 4 & 1\\
\end{bmatrix}
$

$ 1.(-1)^{1+1} 
det = 
\begin{bmatrix}
1 & 1 \\
4 & 1 \\
\end{bmatrix}
$

$ 4.(-1)^{1+2} 
det = 
\begin{bmatrix}
0 & 1 \\
0 & 1 \\
\end{bmatrix}
$

$ 4.(-1)^{1+3} 
det = 
\begin{bmatrix}
0 & 1\\
0 & 4 \\
\end{bmatrix}
$

c11 = 1 (1-4)-4(0-0)+4(0-0) 
    = -3

$
c12 = 
\begin{bmatrix}
0 & 4 & 4\\
-1 & 1 & 1 \\
2 & 4 & 1\\
\end{bmatrix}
$

$ 0.(-1)^{1+1} 
det = 
\begin{bmatrix}
1 & 1 \\
4 & 1 \\
\end{bmatrix}
$

$ 4.(-1)^{1+2} 
det = 
\begin{bmatrix}
-1 & 1 \\
2 & 1 \\
\end{bmatrix}
$

$ 4.(-1)^{1+3} 
det = 
\begin{bmatrix}
-1 & 1\\
2 & 4 \\
\end{bmatrix}
$

c12 = 0(1-4)-4(-1-2)+4(-4-2)
    = -12

$
c13 = 
\begin{bmatrix}
0 & 1 & 4\\
-1 & 0 & 1 \\
2 & 0 & 1\\
\end{bmatrix}
$

$ 0.(-1)^{1+1} 
det = 
\begin{bmatrix}
0 & 1 \\
0 & 1 \\
\end{bmatrix}
$

$ 1.(-1)^{1+2} 
det = 
\begin{bmatrix}
-1 & 1 \\
2 & 1 \\
\end{bmatrix}
$

$ 4.(-1)^{1+3} 
det = 
\begin{bmatrix}
-1 & 0\\
2 & 0 \\
\end{bmatrix}
$

c13 = 0(0-0)-1(1-2)+4(0-2)
    = 3

$
c14 = 
\begin{bmatrix}
0 & 1 & 4\\
-1 & 0 & 1 \\
2 & 0 & 4\\
\end{bmatrix}
$

$ 0.(-1)^{1+1} 
det = 
\begin{bmatrix}
0 & 1 \\
0 & 4 \\
\end{bmatrix}
$

$ 1.(-1)^{1+2} 
det = 
\begin{bmatrix}
-1 & 1 \\
2 & 4 \\
\end{bmatrix}
$

$ 4.(-1)^{1+3} 
det = 
\begin{bmatrix}
-1 & 0\\
2 & 0 \\
\end{bmatrix}
$

c14 = 0(0-0)-1(-4-2)+4(0-0)
    = 6

$ A = 
\begin{bmatrix}
1 & 4 & 2 & 3\\
0 & 1 & 4 & 4\\
-1 & 0 & 1 & 1\\
2 & 0 & 4 & 1
\end{bmatrix}
$

= a11c11 + a12c12 + a13c13 + a14c14

= 1.(-3)-4(-12)+2(3)-3(6)

= -3 + 48 + 6 - 18

= 33