# Sistem Linier

Sistem linier merupakan sekumpulan persamaan linier yang terdiri dari beberapa variabel. yang dapat ditulis sebagai berikut : 

3x + 2y - z = 1

2x - 2y + 4z = -2

Pada sistem di atas terdiri dari tiga variabel x, y, z. Kata "sistem" disini penting karena menunjukkan bahwa persamaan-persamaannya saling berkaitan dan tidak dapat dipisahkan. Nilai variabel-variabel dalam sistem ditemtukan secara bersamaan bukan secara individual.

Ada tiga kemungkinan solusi yang dapat terjadi pada sistem persamaan linier :

### 1. Mempunyai solusi tunggal
#### Contoh : 
Pada persamaan ini, Sistem persamaan linier (SPL) memiliki satu solusi yang dapat memenuhi semua persamaan dalam sistem. Solusi ini dapat direpresentasikan sebagai nilai unik untuk setiap variabel (x, y, z, dst.).

x + y = 2

2x - y = 1


### 2. Mempunyai banyak solusi
#### Contoh :
kasus ini terjadi ketika Sistem Persamaan Linier (SPL) memiliki solusi tak terhingga banyaknya. Artinya terdapat banyak kombinasi nilai variabel yang memenuhi semua persamaan pada sistem. Solusi ini dapat direpresentasikan sebagai himpunan solusi, dimana setiap elemennya adalah kombinasi nilai variabel yang memenuhi Sistem Persamaan Linier.

x + y = 2

2x + 2y = 4

nilai x dan y dapat berupa bilangan real apa pun asalkan memenuhi persamaan x + y = 2

### 3. Tidak mempunyai solusi
#### Contoh :
Kasus ini terjadi ketika tidak ada kombinasi nilai variabel yang memenuhi semua persamaan dalam sistem. Sistem Persamaan Linier ini disebut inkonsisten karena tidak memiliki solusi yang valid.

x + y = 2

2x + y = 3

Pada persamaan diatas tidak memiliki solusi karena tidak ada nilai x dan y yang dapat memenuhi kedua persamaan secara bersamaan.


## Operasi Baris dan Eliminasi

Eliminasi merupakan menukar sistem yang ada dengan sistem lain yang juga memiliki penyelesaian yang sama.

kita buat array numpy dan akan diberi nama pada array A sehingga kita dapat melihatnya nanti. 

In [1]:
import numpy as np 

A = np.array ([[8,9,1,19],[1,2,3,9],[2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


Kemudian kita akan memulai operasi pada array ini. akan tetapi sebelumnya kita akan menulis code python yang akan digunakan selama perhitungan nanti.

In [2]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

Pertama menukan baris pertama dengan baris kedua matriks, Sehingga :

In [3]:
A1 = RowSwap(A,0,1)
print(A1)

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]]


In [4]:
# Menambahkan -8 kali baris 0 ke baris 1
A2 = RowAdd(A1,0,1,-8)
print(A2)

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]]


In [5]:
# Menambahkan -2 kali balis 0 ke baris 2
A3 = RowAdd(A2,0,2,-2)
print(A3)

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]]


In [6]:
# Mengalikan baris 1 dengan -1/7
A4 = RowScale(A3,1,-1/7)
print(A4)

[[  1.           2.           3.           9.        ]
 [ -0.           1.           3.28571429   7.57142857]
 [  0.          -3.          -5.         -13.        ]]


In [7]:
# Menambahkan 3 kali baris 1 ke baris 2
A5 = RowAdd(A4,1,2,3)
print(A5)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          4.85714286  9.71428571]]


In [8]:
# Mengalikan Baris 2 dengan 1/4.85714286
A6 = RowScale(A5,2,1/4.85714286)
print(A6)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          1.          2.        ]]
