# Aljabar Matriks
Matriks merupakan susunan bilangan yang diatur menurut baris dan kolom, dan ditempatkan dalam tanda kurung siku.

In [1]:
# membuat matriks secara manual
import numpy as np
A = np.array([[1,2,3],[4,5,6],[8,7,6]])
B = np.array([[8,5,7],[3,8,6],[4,9,7]])
C = np.array([[5,7,-7],[-3,5,9],])
D = np.array([[8,7,5],[4,-9,10],[8,3,1]])
print(C)

[[ 5  7 -7]
 [-3  5  9]]


In [2]:
# Cara membuat matriks random dan lebih cepat
A = np.random.randint(10,size=(3,3))
print(A)

[[2 1 3]
 [8 9 3]
 [8 6 0]]


## Operasi Matriks
Aljabar Matriks melibatkan operasi matriks, seperti penjumlahan, pengurangan, perkalian dll.

Mari kita pahami pengoperasian matriks.

### Penjumlahan / Pengurangan Matriks
Dua matriks dapat dijumlahkan/dikurangi jika dan hanya jika jumlah baris dan kolom kedua matriks tersebut sama, atau ordo matriksnya sama. 
Untuk Penjumlahan/pengurangan, setiap elemen matriks pertama ditambahkan/dikurangi dengan elemen-elemen yang ada pada matriks kedua.
#### Contoh :
$
\begin{bmatrix}
2 & 0 & 5 \\
3 & 2 & 9
\end{bmatrix} + \begin{bmatrix}
7 & 4 & 1 \\
8 & 13 & 0
\end{bmatrix} = \begin{bmatrix}
9 & 4 & 6 \\
11 & 15 & 9
\end{bmatrix}
$


In [4]:
import numpy as np
A = np.array([[2,0,5],[3,2,9]])
B = np.array([[7,4,1],[8,13,0]])
print(A + B)

[[ 9  4  6]
 [11 15  9]]


### Perkalian Matriks
Matriks dapat dikalikan dengan dua cara 

1. Perkalian Skalar

    Perkalian skalar ini melibatkan besaran skalar dengan matriks. Setiap elemen di dalam matriks harus dikalikan dengan besaran skalar unruk membentuk matriks baru.

    $\
    5\times\begin{bmatrix}
    5&7\\ 
    12&3\\ 
    6&2\end{bmatrix}=\begin{bmatrix}
    25&35\\ 
    60&15\\ 
    30&10\end{bmatrix}
    $

In [6]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
skalar = 2
hasil = skalar * array
print(hasil)


[[ 2  4  6]
 [ 8 10 12]]


2. Perkalian matriks dengan matriks lain
    dua matriks dapat dikalikan jika jumlah kolom matriks pertama sama dengan jumlah baris matriks kedua.
    
    Perhatikan dua matriks dibawah ini.

    $
    \begin{bmatrix}
    1 & 2 & 3 \\
    \end{bmatrix}
    \times\begin{bmatrix}
    2 & 1 & 3\\
    3 & 3 & 2\\
    4 & 1 & 2
    \end{bmatrix} = \begin{bmatrix}
    1.2 + 2.3 + 3.4 & 1.1 + 2.3 + 3.1 & 1.3 + 2.2 + 3.2\\
    \end{bmatrix}
    $

    sehingga :

    $
    \begin{bmatrix}
    1 & 2 & 3 \\
    \end{bmatrix}
    \times\begin{bmatrix}
    2 & 1 & 3\\
    3 & 3 & 2\\
    4 & 1 & 2
    \end{bmatrix} = \begin{bmatrix}
    20 & 10 & 13\\
    \end{bmatrix}
    $

    matriks-matriks diatas memenuhi syarat perkalian matriks, sehingga matriks-matriks tersebut dapat dikalikan.




In [8]:
import numpy as np

A = np.array([[1, 2, 3]])
B = np.array([[2,1,3],[3,3,2],[4,1,2]])
C = A @ B
print(C)


[[20 10 13]]


## Transpose Matriks
Transpose matriks adalah proses menukar elemen-elemen baris menjadi kolom dan juga sebaliknya (kolom menjadi baris). Transpose suatu matriks dinotasikan dengan $A^T$,$A'$
#### Contoh :



In [9]:
A_T = A.transpose()
print(A)
print("\n")
print(A_T)

[[1 2 3]]


[[1]
 [2]
 [3]]


## Matriks Elementer (Kesamaan Dua Matriks)
Matriks A dikatakan sama dengan titik matriks B, jika :
1. Ordo matriks A sama dengan matriks B
2. Semua elemen yang seletak dengan matriks A dan B nilainya sama

#### Contoh : 
$
\begin{bmatrix}
3 & 4+1\\
7 & 9
\end{bmatrix} =
\begin{bmatrix}
\sqrt{9} % 2 
& 5\\
7 & 3^2
\end{bmatrix}
$


3 seletak dengan $\sqrt{9} % 2$

4 + 1 seletak dengan 5

9 seletak dengan $3^2$